# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pVST9eZPe8YUuE6Yb6C3VGnbFDRCEWxG
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Data/flights.csv')

df

from sklearn.preprocessing import MinMaxScaler

scalar_norm = MinMaxScaler()

df['AWND'] = scalar_norm.fit_transform(df[['AWND']])

df.rename(columns={'AWND': 'wind_normalized'}, inplace=True)


df['SNWD'] = scalar_norm.fit_transform(df[['SNWD']])

df.rename(columns={'SNWD': 'snow_on_ground_normalized'}, inplace=True)

df['PRCP'] = scalar_norm.fit_transform(df[['PRCP']])
df.rename(columns={'PRCP': 'precipitation'}, inplace=True)

df['TMAX'] = scalar_norm.fit_transform(df[['TMAX']])
df.rename(columns={'TMAX': 'max_temperature'}, inplace=True)

df['SNOW'] = scalar_norm.fit_transform(df[['SNOW']])

df.rename(columns={'snow_on_ground': 'snow'}, inplace=True)
df
df.to_csv('/content/drive/MyDrive/Data/flights_normalized.csv', index=False)