# -*- coding: utf-8 -*-
"""Final_data_merge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tL15VhB6ACGm5GFJdPrUj7JVPGYLbVtp
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# df_weather = pd.read_csv('/content/drive/MyDrive/Weather Data Project (Southwest Airlines)/Matthew/weather_data_unmerged_2010_to_2023.csv')
# df_weather
df_weather = pd.read_csv('/content/drive/MyDrive/Weather Data Project (Southwest Airlines)/Matthew/weather_extra_airports_2010_to_2023.csv')
df_weather

df_weather.info()

! pip install meteostat

print(df_weather['Origin_Airport'].unique())

# iata_to_station = {
#     "ATL": 72219,
#     "ORD": 72530,
#     "JFK": 74486,
#     "LGA": 74404,
#     "LAX": 72295,
#     "SFO": 72494,
#     "IAH": 72243,
#     "HOU": 72234,
#     "DEN": 72469,
#     "MCO": 72299,
#     "MIA": 72202,
#     "LAS": 72540,
#     "IAD": 72403,
#     "PHX": 72278,
#     "SEA": 72793,
#     "BOS": 74405,
#     "CLT": 72314,
#     "ANC": 70106,
#     "PDX": 72797,
#     "MSP": 72658,
#     "SLC": 72572,
#     "FSD": 72651,
#     "JAC": 70106,
#     "BOI": 72681,
#     "STL": 72434,
#     "BZN": 72681,
#     "DSM": 72434,
#     "ABQ": 72365,
#     "OKC": 72365
# }

icao_codes = {
    "ATL": "KATL",
    "ORD": "KORD",
    "JFK": "KJFK",
    "LGA": "KLGA",
    "LAX": "KLAX",
    "SFO": "KSFO",
    "IAH": "KIAH",
    "HOU": "KHOU",
    "DEN": "KDEN",
    "MCO": "KMCO",
    "MIA": "KMIA",
    "LAS": "KLAS",
    "IAD": "KIAD",
    "PHX": "KPHX",
    "SEA": "KSEA",
    "BOS": "KBOS",
    "CLT": "KCLT",
    "ANC": "PANC",
    "PDX": "KPDX",
    "MSP": "KMSP",
    "SLC": "KSLC",
    "FSD": "KFSD",
    "JAC": "KJAC",
    "BOI": "KBOI",
    "STL": "KSTL",
    "BZN": "KBZN",
    "DSM": "KDSM",
    "ABQ": "KABQ",
    "OKC": "KOKC"
}


df_weather["icao"] = df_weather["Origin_Airport"].map(icao_codes)

df_weather

df_weather["datetime"] = pd.to_datetime(df_weather["datetime"])
df_weather["date"] = df_weather["datetime"].dt.date

import pandas as pd
from meteostat import Stations, Daily


icao_list = df_weather["icao"].unique()


icao_to_wmo = {}


all_stations = Stations().inventory('daily').fetch()

for icao in icao_list:
    match = all_stations[all_stations['icao'] == icao]
    if not match.empty:
        wmo_id = match.iloc[0]['wmo']
        if pd.notnull(wmo_id):
            icao_to_wmo[icao] = int(wmo_id)


daily_list = []

start = df_weather["datetime"].min()
end   = df_weather["datetime"].max()

for icao in icao_list:
    wmo_id = icao_to_wmo.get(icao)
    if not wmo_id:
        continue

    d = Daily(wmo_id, start, end).fetch()
    if d.empty:
        continue

    d = d.reset_index()[["time", "snow"]]
    d["station_id"] = icao
    d.rename(columns={"time": "date", "snow": "snow_mm"}, inplace=True)
    d["date"] = pd.to_datetime(d["date"]).dt.date
    daily_list.append(d)


df_daily_snow = pd.concat(daily_list, ignore_index=True)

print(df_daily_snow.head())

df_daily_snow

df_daily_snow['station_id'].unique()

# from meteostat import Daily

# start = df_weather["datetime"].min()
# end   = df_weather["datetime"].max()

# daily_list = []

# for sid in df_weather["station_id"].unique():
#     d = Daily(sid, start, end).fetch()
#     if d.empty:
#         continue
#     d = d.reset_index()[["time", "snow"]]
#     d["station_id"] = sid
#     d.rename(columns={"time": "date", "snow": "snow_mm"}, inplace=True)
#     d["date"] = pd.to_datetime(d["date"]).dt.date
#     daily_list.append(d)

# df_daily_snow = pd.concat(daily_list, ignore_index=True)

df_weather = df_weather.merge(
    df_daily_snow,
    on=["station_id", "date"],
    how="left"
)

df_weather



# data = pd.read_csv('/content/drive/MyDrive/Weather Data Project (Southwest Airlines)/Matthew/filtered_col_airport_data_2010_to_2023.zip')

data = pd.read_csv('/content/drive/MyDrive/Weather Data Project (Southwest Airlines)/Matthew/final_extra_airports_2010_to_2023.zip')

data

data['datetime'] = pd.to_datetime(data['datetime'], errors='coerce')
df_weather['datetime'] = pd.to_datetime(df_weather['datetime'], errors='coerce')

merged_df = pd.merge(
    data,
    df_weather,
    on=['Origin_Airport', 'datetime'],
    how='inner'   # inner join ensures we only keep flights with weather
)

merged_df

df_test = merged_df[merged_df['sunshine_minutes'] > 0]
df_test

merged_df = merged_df.drop(columns=['snow', 'sunshine_minutes'])

merged_df

merged_df.to_csv("final_version_dataset")

